### PR TITLE
Added 1.20 support

### PR DESCRIPTION
**Pull request by LukaVerzijl**

### CODE REVIEW

**Comment by LukaVerzijl** [comment]
This version DROPS support for minestorm due to chameleon that is not supported anymore on the newest version

**Comment by dev-hydrogen** [comment]
@LukaVerzijl Does chameleon need to be updated for 1.20 support to work? We can just stay on the current version to maintain minestom support.

**Comment by LukaVerzijl** [comment]
@dev-hydrogen no but the minstorm chameleon repo has dropped

**Comment by dev-hydrogen** [comment]
So, im not gonna be merging this unless minestom support can be kept, whether that be by keeping the chameleon version the same or doing it similarly to other cross-platform plugins (e.g how luckperms does it)

**Comment by LukaVerzijl** [comment]
I am not going to add minestorm support sorry for me it is to unstable software to run a server on.

**Pull request closed without merging**
